### ISSUE TITLE
Pertanyaan

### ISSUE THREAD

**Issue by dionstr** [rizdaprasetya/snap-whmcs#1]
Apakah module ini sudah bisa berjalan atau masih tahap development?
Support di WHMCS 7.0.2 tidak?

Thanks ^^

**Comment by rizdaprasetya** [comment]
Plugin sudah bisa digunakan. Namun tidak pernah di tes untuk WHMCS v 7.x
Silahkan dicoba dahulu, jika tidak bisa berarti versi tersebut belum di support.

**Comment by dionstr** [comment]
Terima kasih atas respon nya... akan saya coba dahulu ^^

**Comment by dionstr** [comment]
Setelah saya test menggunakan sandbox sepertinya berjalan dengan baik mas di WHMCS 7.0.2. ^^

Namun untuk bahasa yang tampil apakah ada pilihan bahasa indonesia seperti VT-Web?
Di popup SNAP nya berbahasa english.
kemudian di bagian Button pada viewinvoice (WHMCS) munculnya : Proceed To Payment
lalu di status setelah pilih pembayaran : "Awaiting Payment" dan button dibawahnya  nya "View Payment Instruction" begitu juga dengan instruksi pdf nya masih english. 

Namun untuk instruksi yang dikirimkan ke email pelanggan sudah benar bahasa indonesia.

Mohon dibantu, Terima kasih. :)

**Comment by rizdaprasetya** [comment]
Thanks infonya, terima kasih sudah bantu testing dan memastikan bisa running di versi 7.0.2 👍 
Untuk setting bahasa, silahkan login ke https://account.midtrans.com/login
Kemudian masuk menu `settings > snap preference` akan ada setting `language` yang bisa dipilih, beserta customization menu lainnya. 

Silahkan dicoba :)
